name: dart_database
description: Trabalho de Database Application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  orm: any # O Dart vai buscar a versão estável mais recente
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  prisma: any # Deixe o Dart resolver a versão do CLI
  build_runner: any
  lints: ^3.0.0